In [1]:
import re
str = 'bat, bot, lat let, mot'
ket = re.findall('b[ao]t', str)

print(ket)


['bat', 'bot']


In [2]:
import numpy as np

a1 = np.random.rand(4)
a2 = np.random.rand(4,1)
a3 = np.array([[1,2,3,4]])
a4 = np.arange(1,4,1)
a5 = np.linspace(1 ,4,4)


print(a1)
print(a1.shape)
print('--2----------------')
print(a2)
print(a2.shape)
print('--3----------------')
print(a3)
print(a3.shape)
print('--4----------------')
print(a4)
print(a4.shape)
print('--5----------------')
print(a5)
print(a5.shape)

[0.3213646  0.07140882 0.71840073 0.5707626 ]
(4,)
--2----------------
[[0.34247086]
 [0.06110002]
 [0.1203435 ]
 [0.97668928]]
(4, 1)
--3----------------
[[1 2 3 4]]
(1, 4)
--4----------------
[1 2 3]
(3,)
--5----------------
[1. 2. 3. 4.]
(4,)


In [20]:
old = np.array([[1,1,1],[1,1,1]])
new = old
new[0, :2] = 0
print(old)


[[0 0 1]
 [1 1 1]]


In [30]:
r = np.random.rand(6,6)
print(r)
print('ketqua')
print(r[2:4,2:4])


[[0.04905177 0.5631922  0.17647363 0.6255869  0.76525089 0.5512011 ]
 [0.18981687 0.64012699 0.27810802 0.7108157  0.83085727 0.9335549 ]
 [0.93662824 0.40020186 0.52684965 0.77481399 0.80029898 0.42657508]
 [0.04066798 0.2115935  0.96042168 0.03290465 0.21809374 0.67140867]
 [0.63987624 0.9089039  0.36985967 0.08315256 0.16530975 0.8350522 ]
 [0.85677182 0.1100031  0.87353846 0.5340332  0.62185554 0.97280974]]
ketqua
[[0.52684965 0.77481399]
 [0.96042168 0.03290465]]


In [31]:
s = 'ACBCAC'
re.findall('^AC', s)

['AC']

In [5]:
c = 'ACAABAACAAAB'
tim = re.findall('A{1,2}',c)
print(tim)
le = len(tim)
print(le)


['A', 'AA', 'AA', 'AA', 'A']
5


In [8]:
phone = 'so phone (803) 262-8775, (803) 999-7642.... ,,, lungtung(803) 777-1424het'
so = re.findall('[(]\d{3}[)]\s\d{3}[-]\d{4}',phone)
print(so)

['(803) 262-8775', '(803) 999-7642', '(803) 777-1424']


In [31]:
duong = 'lay duong dan https://www.google.com/ roi tiep https://www.baidi.com, https://www.google.com/doodles/janaina-dutras-61st-birthday crazy day'
#cau lenh lookbehind (?<=) de tim chu ngay sau no va khong gom no trong ket qua
coban = re.findall('(?<=https:\/\/)([A-Za-z0-9.]*)',duong)
print(coban)
#khongDung = re.findall('(?<=https:\/\/)([\d.]*)',duong)
#mo rong them hai dau hoi ?/? de them tuy chon gach cheo / co the co hoac khong 
morong = re.findall('(?<=https:\/\/)([A-Za-z0-9.?/?]*)',duong)
print("Mo Rong")
print(morong)

#minh chua thu tim /
 

['www.google.com', 'www.baidi.com', 'www.google.com']
Mo Rong
['www.google.com/', 'www.baidi.com', 'www.google.com/doodles/janaina']
